OLED_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = no
VIA_ENABLE = no
VIAL_ENABLE = no
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = yes

QMK_SETTINGS = no
MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
